# Generated by Django 3.1.7 on 2021-03-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='detail',
            new_name='content',
        ),
    ]
