# Generated by Django 3.1.7 on 2021-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210316_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='topic',
            field=models.CharField(default='topic', max_length=20),
        ),
    ]
