# Generated by Django 3.1.7 on 2021-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(max_length=1000)),
                ('technology', models.CharField(max_length=20)),
                ('updated', models.DateField()),
                ('bokeh_html', models.TextField(max_length=100000)),
                ('source', models.CharField(max_length=10)),
                ('source_url', models.URLField()),
            ],
        ),
    ]
