# Generated by Django 3.1.7 on 2021-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='download_data_link',
            field=models.URLField(default='dashboard/csv/antipsychotic_presribing_per_capita.csv'),
        ),
    ]
