# Generated by Django 3.1.7 on 2021-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_graph_download_data_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='download_data_link',
            field=models.URLField(),
        ),
    ]
