# Generated by Django 3.1.7 on 2021-03-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210311_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='topic',
            field=models.CharField(default='topic', max_length=20),
        ),
    ]
